name: Publish Release

on:
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: self-hosted
    outputs:
      packages: ${{ steps.packages.outputs.packages }}

    steps:
      - uses: actions/checkout@v4
      - name: Detect Changed Packages
        id: packages
        run: |
          git fetch origin ${{ github.event.before }}
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          CHANGED_PACKAGES=$(cat changed_files.txt | grep -oE '^pkgs/(community|core|experimental|partners|swarmauri)' | cut -d/ -f2 | sort -u | tr '\n' ',' | sed 's/,$//')
    
          if [ -z "$CHANGED_PACKAGES" ]; then
            CHANGED_PACKAGES_ARRAY="[]"
          else
            CHANGED_PACKAGES_ARRAY=$(echo "[\"$(echo $CHANGED_PACKAGES | sed 's/,/","/g')\"]")
          fi

          echo "packages=$CHANGED_PACKAGES_ARRAY" >> $GITHUB_OUTPUT

  build-publish:
    needs: detect-changes
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        package: ${{ fromJSON(needs.detect-changes.outputs.packages) }}

    env: 
      UNIQUE_VENV_PATH: "${{ github.workspace }}/.venv_${{ github.run_id }}_${{ matrix.package }}"
      DANGER_MASTER_PYPI_API_TOKEN: ${{ secrets.DANGER_MASTER_PYPI_API_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Create unique virtual environment for package
        run: |
          UNIQUE_VENV_PATH=".venv_${{ github.run_id }}_${{ matrix.package }}"
          python -m venv $UNIQUE_VENV_PATH

      - name: Install dependencies with Poetry
        run: |
          source $UNIQUE_VENV_PATH/bin/activate
          cd pkgs/${{ matrix.package }}
          poetry install --no-cache -vv --all-extras

      - name: Lint with flake8
        run: |
          source $UNIQUE_VENV_PATH/bin/activate
          cd pkgs/${{ matrix.package }}
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build package with Poetry
        run: |
          source $UNIQUE_VENV_PATH/bin/activate
          cd pkgs/${{ matrix.package }}
          poetry build

      - name: Get pip freeze
        run: |
          source $UNIQUE_VENV_PATH/bin/activate
          pip freeze

      - name: List package sizes
        run: |
          source $UNIQUE_VENV_PATH/bin/activate
          python scripts/list_site_package_sizes.py
        continue-on-error: false

      - name: Show total sitepackage size
        run: |
          source $UNIQUE_VENV_PATH/bin/activate
          python scripts/total_site_packages_size.py
        continue-on-error: false

      - name: Publish to PyPI
        if: github.ref_type == 'tag' && success()  # Only publish on tag
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.DANGER_MASTER_PYPI_API_TOKEN }}
          packages_dir: dist

      - name: Clean up virtual environment
        if: always()
        run: |
          rm -rf ${{ env.UNIQUE_VENV_PATH }}
