[project]
name = "swarmauri_evaluatorpool_accessibility"
version = "0.1.0"
description = "A package providing accessibility and readability evaluators for SwarmAuri"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/swarmauri/swarmauri-sdk/pkgs/standards/swarmauri_evaluatorpool_accessibility/"
requires-python = ">=3.10,<3.13"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Linguistic",
    "Topic :: Software Development :: Quality Assurance"
]
authors = [
    { name = "SwarmAuri Team", email = "info@swarmauri.com" }
]
keywords = [
    "accessibility",
    "readability",
    "evaluator",
    "swarmauri",
    "flesch-kincaid",
    "gunning-fog",
    "coleman-liau",
    "automated-readability-index",
    "flesch-reading-ease",
    "text-analysis",
    "nlp"
]
dependencies = [
    "swarmauri_core",
    "swarmauri_base",
    "swarmauri_standard",
    "nltk",
    "beautifulsoup4",
    "markdown",
    "pydantic",
]

[tool.uv.sources]
swarmauri_core = { workspace = true }
swarmauri_base = { workspace = true }
swarmauri_standard = { workspace = true }

[project.entry-points.'swarmauri.evaluator_pools']
AccessibilityEvaluatorPool = "swarmauri_evaluatorpool_accessibility:AccessibilityEvaluatorPool"

[project.entry-points.'swarmauri.evaluators']
AutomatedReadabilityIndexEvaluator = "swarmauri_evaluatorpool_accessibility:AutomatedReadabilityIndexEvaluator"
ColemanLiauIndexEvaluator = "swarmauri_evaluatorpool_accessibility:ColemanLiauIndexEvaluator"
FleschKincaidGradeEvaluator = "swarmauri_evaluatorpool_accessibility:FleschKincaidGradeEvaluator"
FleschReadingEaseEvaluator = "swarmauri_evaluatorpool_accessibility:FleschReadingEaseEvaluator"
GunningFogEvaluator = "swarmauri_evaluatorpool_accessibility:GunningFogEvaluator"

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "unit: Unit tests",
    "integration: Integration tests",
    "regression: Regression tests"
]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312"]

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true