[tool.poetry]
name = "swarmauri-monorepo"
version = "0.6.0.dev1"
description = "Monorepo for multiple interdependent Swarmauri Python packages"
authors = ["Jacob Stewart <jacob@swarmauri.com>"]
# Disables packaging mode
package-mode = false


[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pydantic = "^2.0"

# Path dependencies (editable installs by default)
swarmauri_core = { path = "./core" }
swarmauri_base = { path = "./base" }
swarmauri = { path = "./swarmauri" }
swarmauri_standard = { path = "./standards/swarmauri_standard", extras=["full"] }
swarmauri_community = { path = "./community/swarmauri_community", extras=["full"] }
swm_example_plugin = { path = "./standards/swm_example_plugin" }

[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "^22.3.0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

