[project]
name = "swarmauri-monorepo"
version = "0.6.2.dev3"
description = "Monorepo for multiple interdependent Swarmauri Python packages"
authors = [
	{ name = "Jacob Stewart", email = "jacob@swarmauri.com" },
	]
license = "Apache-2.0"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10,<3.13"

[dependency-groups]
dev = [
"toml>=0.10.2",
"pytest>=8.0.0",
"pytest-xdist>=3.6.1",
"pytest-asyncio>=0.24.0",
"pytest-timeout>=2.3.1",
"pytest-json-report>=1.5.0",
"python-dotenv>=1.0.0",
"pytest-mock>=3.14.0",
"jsonschema>=4.18.5",
"ruff"
]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
	"core",
	"typing",
	"base",
	"swarmauri_standard"
]

[tool.uv.sources]
swarmauri_core = { workspace = true }
swarmauri_typing = { workspace = true }
swarmauri_base = { workspace = true }
swarmauri_standard = { workspace = true }


[tool.pytest.ini_options]
timeout = 300

norecursedirs = ["experimental", "standards/*", "community/*"]

markers = [
    "test: standard test",
    "unit: Unit tests",
    "i9n: Integration Tests",
    "r8n: Regression Tests",
    "timeout: mark test to timeout after X seconds",
    "xfail: Expected failures",
    "xpass: Expected passes",
    "acceptance: Acceptance tests"
]


log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

asyncio_default_fixture_loop_scope = "function"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

