name: "Feature Request"
description: "Submit a feature request to enhance the Swarmauri SDK."
title: "[Feature Request]: "
labels: ["feature request"]
body:
  - type: dropdown
    id: project_root
    attributes:
      label: "Project Root"
      description: "Select the scope of the package."
      options:
        - "core"
        - "base"
        - "mixins"
        - "swarmauri"
        - "community"
        - "experimental"
    validations:
      required: true
      
  - type: input
    id: package_name
    attributes:
      label: "Package Name"
      description: "Provide the name of the package this feature request applies to."
      placeholder: "e.g., swarmauri-sdk-core"
    validations:
      required: true

  - type: input
    id: resource_kind
    attributes:
      label: "Resource Kind"
      description: "Specify the type of resource this feature applies to (e.g., component, utility, etc.)."
      placeholder: "e.g., component"
    validations:
      required: true
      
  - type: input
    id: component_name
    attributes:
      label: "Component Name"
      description: "Provide the name of the package this feature request applies to."
      placeholder: "e.g., AgentBase"
    validations:
      required: true

  - type: dropdown
    id: generate_content
    attributes:
      label: "Generate Content?"
      description: "Would you like to generate additional content with this feature?"
      options:
        - "yes"
        - "no"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "A clear and concise description of the feature you're requesting, including any background context."
      placeholder: "Describe the feature in detail."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Explain why this feature is necessary or how it will benefit the SDK. What problem does it solve?"
      placeholder: "Why do you need this feature?"
    validations:
      required: true

  - type: textarea
    id: potential_solution
    attributes:
      label: "Potential Solution"
      description: "Provide any suggestions for how the feature could be implemented, if applicable."
      placeholder: "Possible implementation or approach."
    validations:
      required: false
