[build-system]
requires = ["meson-python", "ninja", "pybind11", "uv"]
build-backend = "mesonpy"

[project]
name = "IndexBuilder"
version = "0.1.0"
description = "Configuration for package IndexBuilder with C++ extensions using Meson build system."
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.10,<3.13"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
classifiers = [
    "Natural Language :: English",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11", 
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Development Status :: 3 - Alpha"
]

dependencies = [
    "numpy",
    "scipy"
]

[project.optional-dependencies]
dev = ["pytest", "uv"]

[tool.pytest.ini_options]
markers = [
    "unit: Unit tests",
    "i9n: Integration tests",
    "r8n: Regression tests",
    "xfail: Expected failures",
    "xpass: Expected passes"
]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"