[project]
name = "swarmauri_middleware_logging"
version = "0.6.2.dev1"
description = "Middleware for logging requests and responses in Swarmauri applications"
license = "Apache-2.0"
readme = "README.md"
authors = [{name = "Jacob Stewart", email = "jacob@swarmauri.com"}]
requires-python = ">=3.10,<3.13"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Framework :: FastAPI"
]
keywords = [
    "logging",
    "middleware",
    "fastapi",
    "request",
    "response",
    "swarmauri",
    "monitoring",
    "debugging"
]

[dependencies]
swarmauri_core = {workspace = true}
swarmauri_base = {workspace = true}
swarmauri_standard = {workspace = true}
fastapi = {version = ">=0.68.0", extras = ["all"]}
typing-extensions = ">=4.2.0"
python-dotenv = ">=0.19.0"
requests = ">=2.32.3"
uvicorn = {version = ">=0.15.0", optional = true}
python-multipart = ">=0.0.5"

[tool.uv.sources]
swarmauri_core = {workspace = true}
swarmauri_base = {workspace = true}
swarmauri_standard = {workspace = true}

[project.entry-points.'swarmauri.middlewares']
LoggingMiddleware = "swarmauri_middleware_logging:LoggingMiddleware"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.24.0",
    "pytest-xdist>=3.6.1",
    "pytest-json-report>=1.5.0",
    "flake8>=7.0",
    "pytest-timeout>=2.3.1",
    "ruff>=0.9.9",
    "pytest-benchmark>=4.0.0"
]