[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]                          # ← Standard PEP 621 table — uv & Poetry both understand it
name            = "dqueue"
version         = "0.1.0"
description     = "Distributed task queue (FastAPI + WebSocket + Redis Pub/Sub)"
requires-python = ">=3.9"
readme = "README.md"
authors         = [
  { name = "Your Name", email = "you@example.com" },
]

dependencies = [
  "fastapi>=0.111",
  "sqlalchemy>=2.0",
  "uvicorn[standard]>=0.29",
  "redis[hiredis]>=5.0", # provides redis.asyncio
  "pydantic-settings>=2.2",
  "pydantic[email]>=2.7",
  "websockets>=12",
  "httpx[http2]>=0.27",
  "asyncpg>=0.30.0",
  "psycopg2-binary"
]

[project.optional-dependencies]
dev = [
  "pytest>=8.0",
  "ruff>=0.4.0",
]

[project.scripts]                  # simple CLI helper
dqueue-dev = "dqueue.scripts.dev_server:main"

[tool.uv]                          # “uv pattern” → keep venv inside repo, no global cache
virtualenvs.in-project = true
