site_name: Swarmauri SDK
theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/swarmauri/swarmauri-sdk
repo_name: swarmauri/swarmauri-sdk
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - griffe_typingdoc
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
          - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_source: true
- blog:
    blog_dir: news
- tags:
    enabled: true
- search: null
- autorefs: null
nav:
- Home: index.md
- Announcements:
  - news/index.md
- Guide:
  - Installation: guide/installation.md
  - Usage: guide/usage.md
- Foundation:
  - foundation/index.md
  - Core: api/module1.md
  - Base: api/module2.md
  - Standard: api/module2.md
  - Swarmauri: api/module2.md
- Standalone:
  - standalone/index.md
  - First Class: api/module2.md
  - Second Class: api/module2.md
  - Third Class: api/module2.md
extra:
  alternate:
  - name: English
    link: /en/
    lang: en
