site_name: Swarmauri SDK
theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/swarmauri/swarmauri-sdk
repo_name: swarmauri/swarmauri-sdk
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - griffe_typingdoc
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
          - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_source: true
- blog:
    blog_dir: news
- tags:
    enabled: true
- search: null
- autorefs: null
nav:
- Home: index.md
- Announcements:
  - news/index.md
- Guide:
  - Installation: guide/installation.md
  - Usage: guide/usage.md
- Foundation:
  - foundation/index.md
  - Core: api/module1.md
  - Base: api/module2.md
  - Standard: api/module2.md
  - Swarmauri: api/module2.md
- Standalone:
  - standalone/index.md
  - First Class: api/module2.md
  - Second Class: api/module2.md
  - Third Class: api/module2.md
- Stuff:
  - LLMs: src/swarmauri_base/llms/LLMBase.md
  - Chunkers: src/swarmauri_base/chunkers/ChunkerBase.md
- core:
  - Home: src\swarmauri_core\index.md
  - ComponentBase: src\swarmauri_core/ComponentBase\ComponentBase.md
  - ResourceType: src\swarmauri_core/ComponentBase\ResourceType.md
  - ResourceTypes: src\swarmauri_core/ComponentBase\ResourceTypes.md
  - SubclassUnion: src\swarmauri_core/ComponentBase\SubclassUnion.md
  - IAgentCommands: src\swarmauri_core/agent_apis/IAgentCommands\IAgentCommands.md
  - IAgentRouterCRUD: src\swarmauri_core/agent_apis/IAgentRouterCRUD\IAgentRouterCRUD.md
  - IExportConf: src\swarmauri_core/agent_factories/IExportConf\IExportConf.md
  - IAgent: src\swarmauri_core/agents/IAgent\IAgent.md
  - IAgentConversation: src\swarmauri_core/agents/IAgentConversation\IAgentConversation.md
  - IAgentParser: src\swarmauri_core/agents/IAgentParser\IAgentParser.md
  - IAgentRetrieve: src\swarmauri_core/agents/IAgentRetrieve\IAgentRetrieve.md
  - IAgentSystemContext: src\swarmauri_core/agents/IAgentSystemContext\IAgentSystemContext.md
  - IAgentToolkit: src\swarmauri_core/agents/IAgentToolkit\IAgentToolkit.md
  - IAgentVectorStore: src\swarmauri_core/agents/IAgentVectorStore\IAgentVectorStore.md
  - ICallableChain: src\swarmauri_core/chains/ICallableChain\ICallableChain.md
  - IChain: src\swarmauri_core/chains/IChain\IChain.md
  - IChainContext: src\swarmauri_core/chains/IChainContext\IChainContext.md
  - IChainContextLoader: src\swarmauri_core/chains/IChainContextLoader\IChainContextLoader.md
  - IChainFactory: src\swarmauri_core/chains/IChainFactory\IChainFactory.md
  - IChainStep: src\swarmauri_core/chains/IChainStep\IChainStep.md
  - IChunker: src\swarmauri_core/chunkers/IChunker\IChunker.md
  - IControlPlane: src\swarmauri_core/control_panels/IControlPanel\IControlPlane.md
  - IConversation: src\swarmauri_core/conversations/IConversation\IConversation.md
  - IMaxSize: src\swarmauri_core/conversations/IMaxSize\IMaxSize.md
  - ISystemContext: src\swarmauri_core/conversations/ISystemContext\ISystemContext.md
  - IDataConnector: src\swarmauri_core/dataconnectors/IDataConnector\IDataConnector.md
  - IDistanceSimilarity: src\swarmauri_core/distances/IDistanceSimilarity\IDistanceSimilarity.md
  - IDocumentRetrieve: src\swarmauri_core/document_stores/IDocumentRetrieve\IDocumentRetrieve.md
  - IDocumentStore: src\swarmauri_core/document_stores/IDocumentStore\IDocumentStore.md
  - IDocument: src\swarmauri_core/documents/IDocument\IDocument.md
  - IExperimentDocument: src\swarmauri_core/documents/IExperimentDocument\IExperimentDocument.md
  - IFeature: src\swarmauri_core/embeddings/IFeature\IFeature.md
  - ISaveModel: src\swarmauri_core/embeddings/ISaveModel\ISaveModel.md
  - IVectorize: src\swarmauri_core/embeddings/IVectorize\IVectorize.md
  - IExperimentStore: src\swarmauri_core/experiment_stores/IExperimentStore\IExperimentStore.md
  - IFactory: src\swarmauri_core/factories/IFactory\IFactory.md
  - IGenImage: src\swarmauri_core/image_gens/IGenImage\IGenImage.md
  - IFit: src\swarmauri_core/llms/IFit\IFit.md
  - IPredict: src\swarmauri_core/llms/IPredict\IPredict.md
  - IMeasurement: src\swarmauri_core/measurements/IMeasurement\IMeasurement.md
  - IMeasurementAggregate: src\swarmauri_core/measurements/IMeasurementAggregate\IMeasurementAggregate.md
  - IMeasurementCalculate: src\swarmauri_core/measurements/IMeasurementCalculate\IMeasurementCalculate.md
  - IThreshold: src\swarmauri_core/measurements/IThreshold\IThreshold.md
  - IMessage: src\swarmauri_core/messages/IMessage\IMessage.md
  - IParser: src\swarmauri_core/parsers/IParser\IParser.md
  - IPipeline: src\swarmauri_core/pipelines/IPipeline\IPipeline.md
  - PipelineStatus: src\swarmauri_core/pipelines/IPipeline\PipelineStatus.md
  - IPromptTemplate: src\swarmauri_core/prompt_templates/IPromptTemplate\IPromptTemplate.md
  - IPrompt: src\swarmauri_core/prompts/IPrompt\IPrompt.md
  - IPromptMatrix: src\swarmauri_core/prompts/IPromptMatrix\IPromptMatrix.md
  - ITemplate: src\swarmauri_core/prompts/ITemplate\ITemplate.md
  - ISchemaConvert: src\swarmauri_core/schema_converters/ISchemaConvert\ISchemaConvert.md
  - IServiceRegistry: src\swarmauri_core/service_registries/IServiceRegistry\IServiceRegistry.md
  - IAgentRegistrationAPI: src\swarmauri_core/swarm_apis/IAgentRegistrationAPI\IAgentRegistrationAPI.md
  - ISwarmAPI: src\swarmauri_core/swarm_apis/ISwarmAPI\ISwarmAPI.md
  - ISwarm: src\swarmauri_core/swarms/ISwarm\ISwarm.md
  - ITaskMgmtStrategy: src\swarmauri_core/task_mgmt_strategies/ITaskMgmtStrategy\ITaskMgmtStrategy.md
  - IToolkit: src\swarmauri_core/toolkits/IToolkit\IToolkit.md
  - IParameter: src\swarmauri_core/tools/IParameter\IParameter.md
  - ITool: src\swarmauri_core/tools/ITool\ITool.md
  - IChainTracer: src\swarmauri_core/tracing/IChainTracer\IChainTracer.md
  - ITraceContext: src\swarmauri_core/tracing/ITraceContext\ITraceContext.md
  - ITracer: src\swarmauri_core/tracing/ITracer\ITracer.md
  - ITransport: src\swarmauri_core/transports/ITransport\ITransport.md
  - ITransactional: src\swarmauri_core/utils/ITransactional\ITransactional.md
  - IPredictVision: src\swarmauri_core/vcms/IPredictVision\IPredictVision.md
  - ICloudVectorStore: src\swarmauri_core/vector_stores/ICloudVectorStore\ICloudVectorStore.md
  - IPersistentVectorStore: src\swarmauri_core/vector_stores/IPersistentVectorStore\IPersistentVectorStore.md
  - ISimilarity: src\swarmauri_core/vector_stores/ISimilarity\ISimilarity.md
  - IVectorNorm: src\swarmauri_core/vector_stores/IVectorNorm\IVectorNorm.md
  - IVectorStore: src\swarmauri_core/vector_stores/IVectorStore\IVectorStore.md
  - IVectorStoreRetrieve: src\swarmauri_core/vector_stores/IVectorStoreRetrieve\IVectorStoreRetrieve.md
  - IVectorStoreSaveLoad: src\swarmauri_core/vector_stores/IVectorStoreSaveLoad\IVectorStoreSaveLoad.md
  - IVector: src\swarmauri_core/vectors/IVector\IVector.md
  - IVectorMeta: src\swarmauri_core/vectors/IVectorMeta\IVectorMeta.md
  - IVectorProduct: src\swarmauri_core/vectors/IVectorProduct\IVectorProduct.md
- base:
  - Home: src\swarmauri_base\index.md
  - AgentBase: src\swarmauri_base/agents/AgentBase\AgentBase.md
  - AgentConversationMixin: src\swarmauri_base/agents/AgentConversationMixin\AgentConversationMixin.md
  - AgentRetrieveMixin: src\swarmauri_base/agents/AgentRetrieveMixin\AgentRetrieveMixin.md
  - AgentSystemContextMixin: src\swarmauri_base/agents/AgentSystemContextMixin\AgentSystemContextMixin.md
  - AgentToolMixin: src\swarmauri_base/agents/AgentToolMixin\AgentToolMixin.md
  - AgentVectorStoreMixin: src\swarmauri_base/agents/AgentVectorStoreMixin\AgentVectorStoreMixin.md
  - ChainBase: src\swarmauri_base/chains/ChainBase\ChainBase.md
  - ChainContextBase: src\swarmauri_base/chains/ChainContextBase\ChainContextBase.md
  - ChainStepBase: src\swarmauri_base/chains/ChainStepBase\ChainStepBase.md
  - ChunkerBase: src\swarmauri_base/chunkers/ChunkerBase\ChunkerBase.md
  - ControlPanelBase: src\swarmauri_base/control_panels/ControlPanelBase\ControlPanelBase.md
  - ConversationBase: src\swarmauri_base/conversations/ConversationBase\ConversationBase.md
  - ConversationSystemContextMixin: src\swarmauri_base/conversations/ConversationSystemContextMixin\ConversationSystemContextMixin.md
  - DataConnectorBase: src\swarmauri_base/dataconnectors/DataConnectorBase\DataConnectorBase.md
  - DistanceBase: src\swarmauri_base/distances/DistanceBase\DistanceBase.md
  - VisionDistanceBase: src\swarmauri_base/distances/VisionDistanceBase\VisionDistanceBase.md
  - DocumentStoreBase: src\swarmauri_base/document_stores/DocumentStoreBase\DocumentStoreBase.md
  - DocumentStoreRetrieveBase: src\swarmauri_base/document_stores/DocumentStoreRetrieveBase\DocumentStoreRetrieveBase.md
  - DocumentBase: src\swarmauri_base/documents/DocumentBase\DocumentBase.md
  - EmbeddingBase: src\swarmauri_base/embeddings/EmbeddingBase\EmbeddingBase.md
  - VisionEmbeddingBase: src\swarmauri_base/embeddings/VisionEmbeddingBase\VisionEmbeddingBase.md
  - ImageGenBase: src\swarmauri_base/image_gens/ImageGenBase\ImageGenBase.md
  - LLMBase: src\swarmauri_base/llms/LLMBase\LLMBase.md
  - MeasurementAggregateMixin: src\swarmauri_base/measurements/MeasurementAggregateMixin\MeasurementAggregateMixin.md
  - MeasurementBase: src\swarmauri_base/measurements/MeasurementBase\MeasurementBase.md
  - MeasurementCalculateMixin: src\swarmauri_base/measurements/MeasurementCalculateMixin\MeasurementCalculateMixin.md
  - MeasurementThresholdMixin: src\swarmauri_base/measurements/MeasurementThresholdMixin\MeasurementThresholdMixin.md
  - MessageBase: src\swarmauri_base/messages/MessageBase\MessageBase.md
  - ParserBase: src\swarmauri_base/parsers/ParserBase\ParserBase.md
  - PipelineBase: src\swarmauri_base/pipelines/PipelineBase\PipelineBase.md
  - PromptTemplateBase: src\swarmauri_base/prompt_templates/PromptTemplateBase\PromptTemplateBase.md
  - PromptBase: src\swarmauri_base/prompts/PromptBase\PromptBase.md
  - PromptGeneratorBase: src\swarmauri_base/prompts/PromptGeneratorBase\PromptGeneratorBase.md
  - PromptMatrixBase: src\swarmauri_base/prompts/PromptMatrixBase\PromptMatrixBase.md
  - SchemaConverterBase: src\swarmauri_base/schema_converters/SchemaConverterBase\SchemaConverterBase.md
  - ServiceRegistryBase: src\swarmauri_base/service_registries/ServiceRegistryBase\ServiceRegistryBase.md
  - StateBase: src\swarmauri_base/state/StateBase\StateBase.md
  - SwarmBase: src\swarmauri_base/swarms/SwarmBase\SwarmBase.md
  - SwarmStatus: src\swarmauri_base/swarms/SwarmBase\SwarmStatus.md
  - TaskMgmtStrategyBase: src\swarmauri_base/task_mgmt_strategies/TaskMgmtStrategyBase\TaskMgmtStrategyBase.md
  - ToolkitBase: src\swarmauri_base/toolkits/ToolkitBase\ToolkitBase.md
  - ParameterBase: src\swarmauri_base/tools/ParameterBase\ParameterBase.md
  - ToolBase: src\swarmauri_base/tools/ToolBase\ToolBase.md
  - TransportBase: src\swarmauri_base/transports/TransportBase\TransportBase.md
  - TransportProtocol: src\swarmauri_base/transports/TransportBase\TransportProtocol.md
  - VectorStoreBase: src\swarmauri_base/vector_stores/VectorStoreBase\VectorStoreBase.md
  - VectorStoreCloudMixin: src\swarmauri_base/vector_stores/VectorStoreCloudMixin\VectorStoreCloudMixin.md
  - VectorStorePersistentMixin: src\swarmauri_base/vector_stores/VectorStorePersistentMixin\VectorStorePersistentMixin.md
  - VectorStoreRetrieveMixin: src\swarmauri_base/vector_stores/VectorStoreRetrieveMixin\VectorStoreRetrieveMixin.md
  - VectorStoreSaveLoadMixin: src\swarmauri_base/vector_stores/VectorStoreSaveLoadMixin\VectorStoreSaveLoadMixin.md
  - VisionVectorStoreBase: src\swarmauri_base/vector_stores/VisionVectorStoreBase\VisionVectorStoreBase.md
  - VectorBase: src\swarmauri_base/vectors/VectorBase\VectorBase.md
extra:
  alternate:
  - name: English
    link: /en/
    lang: en
