site_name: Swarmauri SDK
repo_url: https://github.com/swarmauri/swarmauri-sdk
repo_name: swarmauri/swarmauri-sdk

theme:
  name: material
  logo: assets/swarmauri_logo_dark.jpeg
  favicon: assets/swarmauri_logo_dark.jpeg
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: orange
      accent: deep orange

  features:
  - announce.dismiss
  - content.action.edit
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  icon:
    repo: fontawesome/brands/github

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - griffe_typingdoc
          show_root_heading: true
          show_if_no_docstring: true
          inherited_members: true
          members_order: source
          separate_signature: true
          unwrap_annotated: true
          filters:
          - '!^_'
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_source: true
- blog:
    blog_dir: news
- tags:
    enabled: true
- search: null
- autorefs: null

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  alternate:
  - name: English
    link: /en/
    lang: en

nav:
- Home: index.md
- Announcements:
  - news/index.md
- Guide:
  - Installation: guide/installation.md
  - Usage: guide/usage.md
- Foundation:
  - foundation/index.md
  - Core: api/module1.md
  - Base: api/module2.md
  - Standard: api/module2.md
  - Swarmauri: api/module2.md
- Standalone:
  - standalone/index.md
  - First Class: api/module2.md
  - Second Class: api/module2.md
  - Third Class: api/module2.md
- core:
  - Home: src/swarmauri_core/index.md
  - ComponentBase: src/swarmauri_core/ComponentBase.md
  - ResourceType: src/swarmauri_core/ResourceType.md
  - ResourceTypes: src/swarmauri_core/ResourceTypes.md
  - SubclassUnion: src/swarmauri_core/SubclassUnion.md
  - IAgentCommands: src/swarmauri_core/agent_apis/IAgentCommands.md
  - IAgentRouterCRUD: src/swarmauri_core/agent_apis/IAgentRouterCRUD.md
  - IExportConf: src/swarmauri_core/agent_factories/IExportConf.md
  - IAgent: src/swarmauri_core/agents/IAgent.md
  - IAgentConversation: src/swarmauri_core/agents/IAgentConversation.md
  - IAgentParser: src/swarmauri_core/agents/IAgentParser.md
  - IAgentRetrieve: src/swarmauri_core/agents/IAgentRetrieve.md
  - IAgentSystemContext: src/swarmauri_core/agents/IAgentSystemContext.md
  - IAgentToolkit: src/swarmauri_core/agents/IAgentToolkit.md
  - IAgentVectorStore: src/swarmauri_core/agents/IAgentVectorStore.md
  - ICallableChain: src/swarmauri_core/chains/ICallableChain.md
  - IChain: src/swarmauri_core/chains/IChain.md
  - IChainContext: src/swarmauri_core/chains/IChainContext.md
  - IChainContextLoader: src/swarmauri_core/chains/IChainContextLoader.md
  - IChainFactory: src/swarmauri_core/chains/IChainFactory.md
  - IChainStep: src/swarmauri_core/chains/IChainStep.md
  - IChunker: src/swarmauri_core/chunkers/IChunker.md
  - IControlPlane: src/swarmauri_core/control_panels/IControlPlane.md
  - IConversation: src/swarmauri_core/conversations/IConversation.md
  - IMaxSize: src/swarmauri_core/conversations/IMaxSize.md
  - ISystemContext: src/swarmauri_core/conversations/ISystemContext.md
  - IDataConnector: src/swarmauri_core/dataconnectors/IDataConnector.md
  - IDistanceSimilarity: src/swarmauri_core/distances/IDistanceSimilarity.md
  - IDocumentRetrieve: src/swarmauri_core/document_stores/IDocumentRetrieve.md
  - IDocumentStore: src/swarmauri_core/document_stores/IDocumentStore.md
  - IDocument: src/swarmauri_core/documents/IDocument.md
  - IExperimentDocument: src/swarmauri_core/documents/IExperimentDocument.md
  - IFeature: src/swarmauri_core/embeddings/IFeature.md
  - ISaveModel: src/swarmauri_core/embeddings/ISaveModel.md
  - IVectorize: src/swarmauri_core/embeddings/IVectorize.md
  # - IExperimentStore: src/swarmauri_core/experiment_stores/IExperimentStore.md
  - IFactory: src/swarmauri_core/factories/IFactory.md
  - IGenImage: src/swarmauri_core/image_gens/IGenImage.md
  - IFit: src/swarmauri_core/llms/IFit.md
  - IPredict: src/swarmauri_core/llms/IPredict.md
  - IMeasurement: src/swarmauri_core/measurements/IMeasurement.md
  - IMeasurementAggregate: src/swarmauri_core/measurements/IMeasurementAggregate.md
  - IMeasurementCalculate: src/swarmauri_core/measurements/IMeasurementCalculate.md
  - IThreshold: src/swarmauri_core/measurements/IThreshold.md
  - IMessage: src/swarmauri_core/messages/IMessage.md
  - IParser: src/swarmauri_core/parsers/IParser.md
  - IPipeline: src/swarmauri_core/pipelines/IPipeline.md
  - PipelineStatus: src/swarmauri_core/pipelines/PipelineStatus.md
  - IPromptTemplate: src/swarmauri_core/prompt_templates/IPromptTemplate.md
  - IPrompt: src/swarmauri_core/prompts/IPrompt.md
  - IPromptMatrix: src/swarmauri_core/prompts/IPromptMatrix.md
  - ITemplate: src/swarmauri_core/prompts/ITemplate.md
  - ISchemaConvert: src/swarmauri_core/schema_converters/ISchemaConvert.md
  - IServiceRegistry: src/swarmauri_core/service_registries/IServiceRegistry.md
  - IAgentRegistrationAPI: src/swarmauri_core/swarm_apis/IAgentRegistrationAPI.md
  - ISwarmAPI: src/swarmauri_core/swarm_apis/ISwarmAPI.md
  - ISwarm: src/swarmauri_core/swarms/ISwarm.md
  - ITaskMgmtStrategy: src/swarmauri_core/task_mgmt_strategies/ITaskMgmtStrategy.md
  - IToolkit: src/swarmauri_core/toolkits/IToolkit.md
  - IParameter: src/swarmauri_core/tools/IParameter.md
  - ITool: src/swarmauri_core/tools/ITool.md
  - IChainTracer: src/swarmauri_core/tracing/IChainTracer.md
  - ITraceContext: src/swarmauri_core/tracing/ITraceContext.md
  - ITracer: src/swarmauri_core/tracing/ITracer.md
  - ITransport: src/swarmauri_core/transports/ITransport.md
  - ITransactional: src/swarmauri_core/utils/ITransactional.md
  - IPredictVision: src/swarmauri_core/vcms/IPredictVision.md
  - ICloudVectorStore: src/swarmauri_core/vector_stores/ICloudVectorStore.md
  - IPersistentVectorStore: src/swarmauri_core/vector_stores/IPersistentVectorStore.md
  - ISimilarity: src/swarmauri_core/vector_stores/ISimilarity.md
  - IVectorNorm: src/swarmauri_core/vector_stores/IVectorNorm.md
  - IVectorStore: src/swarmauri_core/vector_stores/IVectorStore.md
  - IVectorStoreRetrieve: src/swarmauri_core/vector_stores/IVectorStoreRetrieve.md
  - IVectorStoreSaveLoad: src/swarmauri_core/vector_stores/IVectorStoreSaveLoad.md
  - IVector: src/swarmauri_core/vectors/IVector.md
  - IVectorMeta: src/swarmauri_core/vectors/IVectorMeta.md
  - IVectorProduct: src/swarmauri_core/vectors/IVectorProduct.md
- base:
  - Home: src/swarmauri_base/index.md
  - AgentBase: src/swarmauri_base/agents/AgentBase.md
  - AgentConversationMixin: src/swarmauri_base/agents/AgentConversationMixin.md
  - AgentRetrieveMixin: src/swarmauri_base/agents/AgentRetrieveMixin.md
  - AgentSystemContextMixin: src/swarmauri_base/agents/AgentSystemContextMixin.md
  - AgentToolMixin: src/swarmauri_base/agents/AgentToolMixin.md
  - AgentVectorStoreMixin: src/swarmauri_base/agents/AgentVectorStoreMixin.md
  - ChainBase: src/swarmauri_base/chains/ChainBase.md
  - ChainContextBase: src/swarmauri_base/chains/ChainContextBase.md
  - ChainStepBase: src/swarmauri_base/chains/ChainStepBase.md
  - ChunkerBase: src/swarmauri_base/chunkers/ChunkerBase.md
  - ControlPanelBase: src/swarmauri_base/control_panels/ControlPanelBase.md
  - ConversationBase: src/swarmauri_base/conversations/ConversationBase.md
  - ConversationSystemContextMixin: src/swarmauri_base/conversations/ConversationSystemContextMixin.md
  - DataConnectorBase: src/swarmauri_base/dataconnectors/DataConnectorBase.md
  - DistanceBase: src/swarmauri_base/distances/DistanceBase.md
  - VisionDistanceBase: src/swarmauri_base/distances/VisionDistanceBase.md
  - DocumentStoreBase: src/swarmauri_base/document_stores/DocumentStoreBase.md
  - DocumentStoreRetrieveBase: src/swarmauri_base/document_stores/DocumentStoreRetrieveBase.md
  - DocumentBase: src/swarmauri_base/documents/DocumentBase.md
  - EmbeddingBase: src/swarmauri_base/embeddings/EmbeddingBase.md
  - VisionEmbeddingBase: src/swarmauri_base/embeddings/VisionEmbeddingBase.md
  - ImageGenBase: src/swarmauri_base/image_gens/ImageGenBase.md
  - LLMBase: src/swarmauri_base/llms/LLMBase.md
  - MeasurementAggregateMixin: src/swarmauri_base/measurements/MeasurementAggregateMixin.md
  - MeasurementBase: src/swarmauri_base/measurements/MeasurementBase.md
  - MeasurementCalculateMixin: src/swarmauri_base/measurements/MeasurementCalculateMixin.md
  - MeasurementThresholdMixin: src/swarmauri_base/measurements/MeasurementThresholdMixin.md
  - MessageBase: src/swarmauri_base/messages/MessageBase.md
  - ParserBase: src/swarmauri_base/parsers/ParserBase.md
  - PipelineBase: src/swarmauri_base/pipelines/PipelineBase.md
  - PromptTemplateBase: src/swarmauri_base/prompt_templates/PromptTemplateBase.md
  - PromptBase: src/swarmauri_base/prompts/PromptBase.md
  - PromptGeneratorBase: src/swarmauri_base/prompts/PromptGeneratorBase.md
  - PromptMatrixBase: src/swarmauri_base/prompts/PromptMatrixBase.md
  - SchemaConverterBase: src/swarmauri_base/schema_converters/SchemaConverterBase.md
  - ServiceRegistryBase: src/swarmauri_base/service_registries/ServiceRegistryBase.md
  - StateBase: src/swarmauri_base/state/StateBase.md
  - SwarmBase: src/swarmauri_base/swarms/SwarmBase.md
  - SwarmStatus: src/swarmauri_base/swarms/SwarmStatus.md
  - TaskMgmtStrategyBase: src/swarmauri_base/task_mgmt_strategies/TaskMgmtStrategyBase.md
  - ToolkitBase: src/swarmauri_base/toolkits/ToolkitBase.md
  - ParameterBase: src/swarmauri_base/tools/ParameterBase.md
  - ToolBase: src/swarmauri_base/tools/ToolBase.md
  - TransportBase: src/swarmauri_base/transports/TransportBase.md
  - TransportProtocol: src/swarmauri_base/transports/TransportProtocol.md
  - VectorStoreBase: src/swarmauri_base/vector_stores/VectorStoreBase.md
  - VectorStoreCloudMixin: src/swarmauri_base/vector_stores/VectorStoreCloudMixin.md
  - VectorStorePersistentMixin: src/swarmauri_base/vector_stores/VectorStorePersistentMixin.md
  - VectorStoreRetrieveMixin: src/swarmauri_base/vector_stores/VectorStoreRetrieveMixin.md
  - VectorStoreSaveLoadMixin: src/swarmauri_base/vector_stores/VectorStoreSaveLoadMixin.md
  - VisionVectorStoreBase: src/swarmauri_base/vector_stores/VisionVectorStoreBase.md
  - VectorBase: src/swarmauri_base/vectors/VectorBase.md
