# File: .github/workflows/peagen/ci.yaml
name: Peagen CI Deploy

on:
  push:
    branches: [ "master", "mono/dev" ]
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: peagenx               # self-hosted runner with Docker
    # ────────────────────────────────────────────────
    # All variables live in Actions settings
    #   • Secrets → encrypted                     (${ secrets.* })
    #   • Variables → plain, non-secret           (${ vars.* })
    # They are exported to the runner’s env so
    # docker-compose can substitute them directly.
    # ────────────────────────────────────────────────
    env:
      # --- non-secret values (GitHub Variables) ---
      DATA_ROOT:                 /mnt/data
      CONFIG_ROOT:               /mnt/config
      MINIO_ROOT_USER:           minioadmin
      POSTGRES_USER:             npm
      POSTGRES_DB:               npm
      PGADMIN_DEFAULT_EMAIL:     jacob@swarmauri.com

      # --- sensitive values (GitHub *Secrets*) ---
      MINIO_ROOT_PASSWORD:       ${{ secrets.PEAGEN_MINIO_ROOT_PASSWORD }}
      REDIS_PASSWORD:            ${{ secrets.PEAGEN_REDIS_PASSWORD }}
      POSTGRES_PASSWORD:         ${{ secrets.PEAGEN_POSTGRES_PASSWORD }}
      PGADMIN_DEFAULT_PASSWORD:  ${{ secrets.PEAGEN_PGADMIN_PASSWORD }}

    steps:
    # 1) Check out the repo
    - uses: actions/checkout@v4

    # 2) Deploy / refresh the stack
    - name: Deploy with Docker Compose
      working-directory: pkgs/standards/peagen
      run: |
        # Pull latest images (optional—uncomment if desired)
        # sudo docker compose pull

        # Recreate the stack with the env vars already in scope
        sudo docker compose down --remove-orphans
        sudo docker compose up -d --force-recreate
