# File: .github/workflows/peagen_ci.yaml
name: Peagen CI Deploy

on:
  push:
    branches: [ "master", "mono/dev", "coby/peagenv2" ]
    paths:
      - "pkgs/standards/peagen/**"
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: peagenx
    env:
      # --- non-secret values (GitHub Variables) ---
      DATA_ROOT:                 /mnt/data
      CONFIG_ROOT:               /mnt/config
      MINIO_ROOT_USER:           minioadmin
      POSTGRES_USER:             npm
      POSTGRES_DB:               npm

      # --- sensitive values (GitHub *Secrets*) ---
      MINIO_ROOT_PASSWORD:       ${{ secrets.PEAGEN_MINIO_ROOT_PASSWORD }}
      REDIS_PASSWORD:            ${{ secrets.PEAGEN_REDIS_PASSWORD }}
      POSTGRES_PASSWORD:         ${{ secrets.PEAGEN_POSTGRES_PASSWORD }}
      PGADMIN_DEFAULT_PASSWORD:  ${{ secrets.PEAGEN_PGADMIN_PASSWORD }}
      PGADMIN_DEFAULT_EMAIL:     ${{ secrets.PEAGEN_PGADMIN_DEFAULT_EMAIL }}


    steps:
    # 1) Check out the repo
    - uses: actions/checkout@v4

    # 2) Deploy / refresh the stack
    - name: Deploy with Docker Compose
      run: |
        cd pkgs/standards/peagen
        # Pull latest images (optional—uncomment if desired)
        # sudo -E docker-compose pull

        # Recreate the stack with the env vars already in scope
        sudo -E docker-compose down --remove-orphans
        sudo -E docker-compose up -d --force-recreate --build
