name: 0.6.0 - Prepare, Install, Validate

on:
  push:
    branches: [ "mono/0.6.0.dev1" ]

jobs:
  install-prepare-validate:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3. Install project dependencies via Poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install soliloquy=="0.1.1.dev54"

      # 4. Run the install phase
      ## This will create one lock file
      ## If we want to create a lock file per folder then we use "recursive"
      - name: Run install phase
        run: |
          cd pkgs
          soliloquy install --directory .

      # 5. Run the prepare phase
      - name: Run prepare phase
        run: |
          # This example bumps the patch version and uses a custom commit message.
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          cd pkgs
          soliloquy prepare --directory . --recursive --bump patch --commit-msg "chore: auto prepare" --disable-lint


      # 6. Run the validate phase
      - name: Run validate phase
        run: |
          cd pkgs
          soliloquy validate --directory . --recursive --test-mode each --num-workers 4
