name: Install Packages - v0.6.0.dev1

on:
  push:

jobs:
  test:
    env:
      UNIQUE_VENV_PATH: "${{ github.workspace }}/.venv_core_${{ github.run_id }}"
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

    - name: Install All Packages
      run: |
        python -m venv $UNIQUE_VENV_PATH
        source $UNIQUE_VENV_PATH/bin/activate
        cd pkgs/
        poetry install --no-cache -vv --all-extras

    - name: Install and Build All Sub-Packages
      run: |
        source $UNIQUE_VENV_PATH/bin/activate
        for package in pkgs/*; do
          if [ -d "$package" ] && [ -f "$package/pyproject.toml" ]; then
            echo "Processing $package"
            cd "$package"
            poetry install --no-cache -vv --all-extras
            poetry build
            cd -
          fi
        done

    - name: Clean up virtual environment
      if: always()
      run: |
        rm -rf ${{ env.UNIQUE_VENV_PATH }}
